baseURL = 'https://b.oui.moe/'
languageCode = 'zh-cn'
title = '·≤òêëº'
theme = 'paper'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  github = 'Yulxon'
  rss = true                                # show rss icon

  # home page profile
  name = ''
  bio = ''

  # misc
  disableHLJS = false                        # disable highlight.js
  disablePostNavigation = false              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  math = true                               # enable KaTeX math typesetting globally
  localKatex = false                        # use local KaTeX js/css instead of CDN

